// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        return unsupported;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );

  static const FirebaseOptions unsupported = FirebaseOptions(
    apiKey: "AIzaSyDBqcfwbFnu8GKAz5MMIhqRwUgMLjN0K-U",
    authDomain: "smart-plug-and-energy-meter.firebaseapp.com",
    databaseURL:
        "https://smart-plug-and-energy-meter-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "smart-plug-and-energy-meter",
    storageBucket: "smart-plug-and-energy-meter.firebasestorage.app",
    messagingSenderId: "163950309353",
    appId: "1:163950309353:web:3b00a96478d7d0ce066578",
    measurementId: "G-5Q92FQ78LZ",
  );
}
